[env]
ANDROID_HOME = "C:/Users/mazin/Android/Sdk"
NDK_HOME = "C:/Users/mazin/Android/Sdk/ndk/29.0.13846066"
JAVA_HOME = "C:/Program Files/Microsoft/jdk-21.0.10.7-hotspot"

[target.aarch64-linux-android]
linker = "C:/Users/mazin/Android/Sdk/ndk/29.0.13846066/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android24-clang.cmd"

[target.armv7-linux-androideabi]
linker = "C:/Users/mazin/Android/Sdk/ndk/29.0.13846066/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi24-clang.cmd"

[target.x86_64-linux-android]
linker = "C:/Users/mazin/Android/Sdk/ndk/29.0.13846066/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android24-clang.cmd"

[target.i686-linux-android]
linker = "C:/Users/mazin/Android/Sdk/ndk/29.0.13846066/toolchains/llvm/prebuilt/windows-x86_64/bin/i686-linux-android24-clang.cmd"
